### ISSUE TITLE
Works great - thanks!

### ISSUE THREAD

**Issue by RetroFloppySupport** [rwtodd/bascat#1]
I had to install a Go compiler to run it - maybe others would appreciate a "release" that includes binaries?

Anyway - it worked perfectly for me, and I've had trouble finding a reliable BASICA detokenizer.  Finally I have one!  Thanks!

**Comment by rwtodd** [comment]
Since it looks like you use java regularly, I'd like to point out that other branches of this repo have java/scala/clojure versions, and they all should pretty much work the same way.

As for releases, I kind-of feel like people who need to decode BASICA files probably also are ok with picking one of the implementations and compiling it. But, I've never looked into it and if it's easy to do I'll certainly add a binary release (probably the Go or C or Rust version).  Thanks for the suggestion and I'm glad the code worked for you.

**Comment by RetroFloppySupport** [comment]
> Since it looks like you use java regularly, I'd like to point out that other branches of this repo have java/scala/clojure versions, and they all should pretty much work the same way.

Good to know.  If I had realized that, I would have gone the Java route.  But now I have a Go compiler as a bonus!

> As for releases, I kind-of feel like people who need to decode BASICA files probably also are ok with picking one of the implementations and compiling it.

Well, in the sample size of one, I did just that.

> But, I've never looked into it and if it's easy to do I'll certainly add a binary release (probably the Go or C or Rust version). Thanks for the suggestion and I'm glad the code worked for you.

Yeah, a binary executable version would probably make the most sense and cause the least headaches (no prereqs to install).  But then that puts the onus on you to build binaries for potentially "foreign" (to you) platforms.  Maybe git "actions" would be useful to do that build work for you.  Anyway, no longer a priority from my perspective!  Thanks again.
